import { useMemo } from 'react';
import { Sparkles, ArrowRight, Info } from 'lucide-react';
import { clsx } from '@/lib/clsx';
import { useApp } from '@/state/store';
import { getAlgorithm } from '@/algorithms/registry';
import { explainFor } from '@/algorithms/explain';
import { ALGORITHM_FAMILIES } from '@/algorithms/registry';
import { fmtMs } from '@/lib/format';

/**
 * The "ACTIVE ALGORITHM" hero strip — shows what is routing right now and why,
 * with a live explanation generated by the algorithm itself.
 */
export function ActiveAlgorithmBanner() {
  const snapshot = useApp((s) => s.snapshot);
  const setWhyOpen = useApp((s) => s.setWhyOpen);
  const active = snapshot.activeAlgorithm;
  const definition = getAlgorithm(active);

  const explanation = useMemo(() => {
    if (!definition) return 'Custom algorithm supplied from the playground.';
    return explainFor(definition, snapshot.servers, snapshot.simTime);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [definition, snapshot.simTime, snapshot.servers.length, snapshot.activeAlgorithm]);

  const family = definition ? ALGORITHM_FAMILIES[definition.family] : null;
  const decision = snapshot.autopilot.lastDecision;
  const autopilotOn = snapshot.autopilot.enabled;

  return (
    <div
      className={clsx(
        'relative overflow-hidden rounded-2xl border p-4',
        autopilotOn
          ? 'border-neon-violet/30 bg-gradient-to-r from-neon-violet/[0.12] via-white/[0.02] to-transparent'
          : 'border-white/[0.08] bg-gradient-to-r from-neon-cyan/[0.09] via-white/[0.02] to-transparent',
      )}
    >
      <div className="pointer-events-none absolute -right-16 -top-24 h-64 w-64 rounded-full bg-neon-cyan/10 blur-3xl" />
      <div className="flex flex-wrap items-start justify-between gap-4">
        <div className="min-w-0 flex-1">
          <div className="flex items-center gap-2">
            <span className="eyebrow">Active algorithm</span>
            {autopilotOn && (
              <span className="chip animate-pulse border-neon-violet/40 bg-neon-violet/15 text-[10px] text-[#c3b9ff]">
                <Sparkles className="h-2.5 w-2.5" /> AI selected
              </span>
            )}
          </div>

          <div className="mt-1 flex flex-wrap items-baseline gap-3">
            <h2 className="font-display text-[26px] font-bold leading-none tracking-tight text-white sm:text-[30px]">
              {snapshot.activeAlgorithmName}
            </h2>
            {family && (
              <span
                className="rounded-md border px-2 py-[3px] font-mono text-[10px] font-bold uppercase tracking-wider"
                style={{ color: family.color, borderColor: `${family.color}44`, background: `${family.color}14` }}
              >
                {family.label}
              </span>
            )}
            {decision && autopilotOn && (
              <span className="font-mono text-[11px] text-slate-500">
                switched {snapshot.autopilot.switches}× · confidence {(decision.confidence * 100).toFixed(0)}%
              </span>
            )}
          </div>

          <div className="mt-2.5 flex items-start gap-2 rounded-lg border border-white/[0.06] bg-black/25 px-3 py-2">
            <Info className="mt-[2px] h-3.5 w-3.5 shrink-0 text-neon-cyan/70" />
            <div>
              <span className="text-[11px] font-semibold uppercase tracking-[0.14em] text-slate-500">Why? </span>
              <span className="text-[12.5px] leading-relaxed text-slate-300">{explanation}</span>
            </div>
          </div>
        </div>

        <div className="flex shrink-0 flex-col items-end gap-2">
          <div className="flex gap-4">
            <MiniStat label="Throughput" value={`${snapshot.metrics.throughput.toFixed(0)}`} unit="rps" />
            <MiniStat label="Avg latency" value={fmtMs(snapshot.metrics.avgLatencyMs)} />
            <MiniStat
              label="Errors"
              value={`${(snapshot.metrics.errorRate * 100).toFixed(2)}%`}
              tone={snapshot.metrics.errorRate > 0.03 ? 'bad' : 'good'}
            />
          </div>
          {autopilotOn && (
            <button type="button" className="btn btn-violet text-[12px]" onClick={() => setWhyOpen(true)}>
              <Sparkles className="h-3.5 w-3.5" /> Why did AI choose this?
            </button>
          )}
          {!autopilotOn && definition && (
            <span className="flex items-center gap-1 font-mono text-[10.5px] text-slate-600">
              manual control <ArrowRight className="h-3 w-3" />
            </span>
          )}
        </div>
      </div>
    </div>
  );
}

function MiniStat({ label, value, unit, tone }: { label: string; value: string; unit?: string; tone?: 'good' | 'bad' }) {
  return (
    <div className="text-right">
      <div className="eyebrow">{label}</div>
      <div
        className={clsx(
          'num mt-0.5 font-display text-[16px] font-semibold leading-none',
          tone === 'bad' ? 'text-neon-rose' : tone === 'good' ? 'text-neon-mint' : 'text-slate-100',
        )}
      >
        {value}
        {unit && <span className="ml-1 text-[10px] font-normal text-slate-500">{unit}</span>}
      </div>
    </div>
  );
}
